language: objective-c

matrix:
  include:
    - osx_image: xcode9.3
    - osx_image: xcode10.1
    - osx_image: xcode10.2

script:
  make ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
