fastlane_version "1.89.0"

default_platform :mac

platform :mac do

  desc "Runs all the tests"
  lane :test do
    swiftlint
  	sh "swift test"
  end

  desc "Clean the build artifacts"
  lane :clean do
    sh 'swift build --clean'
  end

  desc "Run :clean and build the executable in release configuration"
  lane :release do
    clean
    sh 'swift build --configuration release'
  end

end
